### PR TITLE
Add carthage support, app extension compliance, and bitcode

### PR DESCRIPTION
**Pull request by ethansinjin**
Also adds a standard .gitignore

### CODE REVIEW

**Comment by mattt** [comment]
Thanks for your PR, @ethansinjin. I apologize for taking so long to review this.

I've since made some pretty involved changes to the project file and directory structure. Can you please confirm whether the latest version of Godzippa works as expected with Carthage? If not, what additional changes need to be made?

**Comment by ethansinjin** [comment]
Hey, no problem, thanks for getting back to me!
Unfortunately, I've since stopped using this project, but I'll cc one of my former coworkers who may know if the issue is still occurring. 

// cc @n8chur

**Comment by n8chur** [comment]
Thanks for cc'ing me @ethansinjin, and thanks for responding to this @mattt!

I'll try with the latest release and report back.

**Comment by n8chur** [comment]
@mattt: `2.0.0` Carthage support works great! Thanks!

**Comment by mattt** [comment]
Great! Thanks for letting me know, @n8chur 👍

**Pull request closed without merging**
